// Scrapes base stats / types / size for every rostered Pokemon from pokemondb.net
// and writes js/data/pokemon.js. Run: node tools/fetch-pokemon.mjs
import { writeFileSync } from 'node:fs';
import { TEAMS } from '../js/data/teams.js';

const SPRITE = 'https://img.pokemondb.net/sprites';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const slugs = [...new Set(TEAMS.flatMap((t) => Object.values(t.roster).map((r) => r.mon)))];

function firstMatch(html, re) {
  const m = html.match(re);
  return m ? m[1] : null;
}

function statAfter(html, label) {
  const i = html.indexOf(`<th>${label}</th>`);
  if (i < 0) throw new Error(`missing ${label}`);
  const m = html.slice(i).match(/<td class="cell-num">(\d+)<\/td>/);
  return Number(m[1]);
}

async function exists(url) {
  const res = await fetch(url, { method: 'HEAD' });
  return res.ok;
}

async function spriteSlug(set, slug, ext) {
  for (const s of [slug, `${slug}-midday`, `${slug}-disguised`, `${slug}-male`, `${slug}-normal`, `${slug}-average`, `${slug}-standard`]) {
    if (await exists(`${SPRITE}/${set}/${s}.${ext}`)) return s;
  }
  return null;
}

const out = {};
for (const slug of slugs) {
  const res = await fetch(`https://pokemondb.net/pokedex/${slug}`);
  if (!res.ok) throw new Error(`${slug}: HTTP ${res.status}`);
  const html = await res.text();
  const name = firstMatch(html, /<h1>([^<]+)<\/h1>/).trim();
  const dex = Number(firstMatch(html, /<th>National (?:№|&#8470;)<\/th>\s*<td><strong>(\d+)<\/strong>/));
  const typeCell = html.slice(html.indexOf('<th>Type</th>')).split('</td>')[0];
  const types = [...typeCell.matchAll(/type-icon type-(\w+)/g)].map((m) => m[1]);
  const height = Number(firstMatch(html, /<th>Height<\/th>\s*<td>([\d.]+)&nbsp;m/));
  const weight = Number(firstMatch(html, /<th>Weight<\/th>\s*<td>([\d.]+)&nbsp;kg/));
  const stats = {
    hp: statAfter(html, 'HP'), atk: statAfter(html, 'Attack'), def: statAfter(html, 'Defense'),
    spa: statAfter(html, 'Sp. Atk'), spd: statAfter(html, 'Sp. Def'), spe: statAfter(html, 'Speed'),
  };
  const home = await spriteSlug('home/normal', slug, 'png');
  const bw = dex <= 649 ? await spriteSlug('black-white/anim/normal', slug, 'gif') : null;
  out[slug] = { name: name.replace(/&#039;|&#39;/g, "'").replace(/&eacute;/g, 'é'), dex, types, height, weight, stats, sprites: { home, bw } };
  console.log(`${slug.padEnd(12)} #${dex} ${types.join('/')} ${JSON.stringify(stats)} home=${home} bw=${bw}`);
  await sleep(250);
}

const header = '// AUTO-GENERATED by tools/fetch-pokemon.mjs from pokemondb.net — do not edit by hand.\n';
writeFileSync(new URL('../js/data/pokemon.js', import.meta.url),
  `${header}export const POKEMON = ${JSON.stringify(out, null, 1)};\n`);
console.log(`Wrote ${slugs.length} Pokemon.`);
